export { default as Grade1Icon } from './grades/Grade1Icon.vue'
export { default as Grade2Icon } from './grades/Grade2Icon.vue'
export { default as Grade3Icon } from './grades/Grade3Icon.vue'
export { default as Grade4Icon } from './grades/Grade4Icon.vue'
export { default as Grade5Icon } from './grades/Grade5Icon.vue'
export { default as RawIcon } from './materialTypes/RawIcon.vue'
export { default as EncodedIcon } from './materialTypes/EncodedIcon.vue'
export { default as ManufacturedIcon } from './materialTypes/ManufacturedIcon.vue'
